### ISSUE TITLE
Improving smart select ?

### ISSUE THREAD

**Issue by Fred-Vatin** [RechInformatica/rech-editor-batch#12]
Hi,

Do you think your extension can help VScode to better manage smart select in batch files as explained [here](https://github.com/microsoft/vscode/issues/108763) ?

I tested with the built-in **Windows Bat Language Basics** extension alone then both then only yours.

**Comment by gustavosimon** [comment]
Hello @Fred-Vatin ! Thanks for opening this issue.

Do you still have this doubt?

**Comment by Fred-Vatin** [comment]
I use an extension to select text between `" ' [ { (`. No problem anymore.

**Comment by gustavosimon** [comment]
Got it... So can we close this issue?

**Comment by Fred-Vatin** [comment]
Yes

**Comment by gustavosimon** [comment]
Nice. Thank u @Fred-Vatin. I'm going to close this issue.
