### ISSUE TITLE
Extension forces tab key to insert 4 spaces

### ISSUE THREAD

**Issue by Fred-Vatin** [RechInformatica/rech-editor-batch#14]
VS Code version | OS | Extension version
------------------ | ---- | ----
1.52.0  | Win 10 x64 pro (french) 18363.*| 0.0.19

## Steps to reproduce

1. Press tab key

## Results

Always insert 4 spaces no matters the VSCode settings.

## Expectations

Don’t override VSCode settings.

**Comment by psteiner** [comment]
Also experiencing this minor annoyance, any chance it can be fixed?

**Comment by gustavosimon** [comment]
Hello @Fred-Vatin and @psteiner ! Thanks for taking us feedback about this behavior. 

We're going to fix this! I'm going to handle this as an improvement.
