### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by reconsumeralization** [RechInformatica/rech-editor-batch#16]
- Issue Type: `Performance`
- Extension Name: `rech-editor-batch`
- Extension Version: `0.0.19`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Amber\AppData\Local\Temp\rechinformatica.rech-editor-batch-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by gustavosimon** [comment]
Hello @reconsumeralization! Thanks for opening this issue!

Do you still taking this performance problem with our extension?

**Comment by gustavosimon** [comment]
Hello @reconsumeralization !

I would like to know if you still taking this performance problem with out extension, otherwise I will close this issue.

**Comment by reconsumeralization** [comment]
Turns out it was just that computers time to die :)
