### ISSUE TITLE
Add support for *.cmd extension, not only *.bat

### ISSUE THREAD

**Issue by scanbix** [RechInformatica/rech-editor-batch#5]
Hello,

CMD extension is valid script file extension for windows. It has slight differences from BAT files.

Thank you

**Comment by GustavoASC** [comment]
@scanbix Thank you for opening this issue! We'll take a look at this on the next days, as soon as we have a free time. 👍

**Comment by GustavoASC** [comment]
Hi @scanbix,

We've just published v0.0.17 with support for *.cmd extensions 👍

**Comment by scanbix** [comment]
Cool, thank you so much. I will take a look tonight :)
